name: ocdit

channels:
   - conda-forge
   - pytorch
   - nvidia

dependencies:
  - python=3.12
  - pip

  # torch
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8




